name: CI tomee-7.1.x-TT.x

on:
  push:
    branches:
      - tomee-7.1.x-TT.x
  pull_request:
    branches:
      - tomee-7.1.x-TT.x
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Apache Maven Central
      uses: actions/setup-java@v1
      with: # running setup-java again overwrites the settings.xml
        java-version: 1.8
        server-id: maven # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_PASSWORD # env variable for token in deploy

    - name: Build with Maven
      run: mvn --show-version -U --fail-at-end clean install -DfailIfNoTests=false -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}