name: CI tomee-7.1.x-TT.x

on:
  push:
    branches:
      - tomee-7.1.x-TT.x
  pull_request:
    branches:
      - tomee-7.1.x-TT.x
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: joschi/setup-jdk@v2
      with:
        java-version: '8'
        server-id: tomitribe-all
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v9
      with:
        repositories: '[{ "id": "tomitribe-all", "url": "https://repository.tomitribe.com/content/groups/tomitribe/", "releases": { "enabled": "true" } }]'
        plugin_repositories: '[{ "id": "tomitribe-all", "url": "https://repository.tomitribe.com/content/groups/tomitribe/", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" }  }]'
        servers: '[{ "id": "tomitribe-all", "username": "${{secrets.MAVEN_USERNAME}}", "password": "${{secrets.MAVEN_PASSWORD}}" }]'

    - name: Build with Maven
      run: mvn --show-version -U --fail-at-end clean install -DfailIfNoTests=false -DskipTests